# Generated by Django 5.0.6 on 2025-08-16 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='laudo',
            field=models.FileField(blank=True, null=True, upload_to='laudos_alunos/', verbose_name='Laudo (PDF ou Imagem)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nivel_autismo',
            field=models.IntegerField(blank=True, choices=[(1, 'Nível 1 - Exige apoio'), (2, 'Nível 2 - Exige apoio substancial'), (3, 'Nível 3 - Exige apoio muito substancial')], null=True, verbose_name='Nível de Suporte (Autismo)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.turma', verbose_name='Turma Regular'),
        ),
    ]
