# Generated by Django 5.2.1 on 2025-05-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem_url', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('horario_funcionamento', models.CharField(max_length=100)),
                ('avaliacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('tipo', models.CharField(choices=[('CLINICA', 'Clínica'), ('PROFISSIONAL', 'Profissional'), ('ASSOCIACAO', 'Associação'), ('ESCOLA', 'Escola'), ('GRUPO_APOIO', 'Grupo de Apoio'), ('EMERGENCIA', 'Emergência')], max_length=20)),
                ('atendimento_presencial', models.BooleanField(default=True)),
                ('atendimento_online', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
