# Generated by Django 5.2.1 on 2025-05-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone_classe', models.CharField(default='fas fa-tools', max_length=50)),
                ('eh_gratuita', models.BooleanField(default=False)),
                ('classificacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('categoria', models.CharField(choices=[('comunicacao', 'Ferramentas de Comunicação'), ('comportamental', 'Ferramentas Comportamentais'), ('educacional', 'Ferramentas Educacionais'), ('organizacao', 'Ferramentas de Organização'), ('sensorial', 'Ferramentas Sensoriais'), ('tecnologica', 'Ferramentas de Tecnologia Assistiva')], max_length=100)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='core.tipoferramenta')),
            ],
        ),
    ]
