# Generated by Django 5.0.6 on 2025-08-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_turma_aluno_laudo_aluno_nivel_autismo_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='core.categoriaferramenta'),
        ),
    ]
