# Generated by Django 5.0.6 on 2025-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ferramenta_tipo_alter_ferramenta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='apenas_para_professores',
            field=models.BooleanField(default=False, verbose_name='Apenas para professores?'),
        ),
    ]
