# Generated by Django 5.0.6 on 2025-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ferramenta_apenas_para_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='O arquivo PDF da ferramenta para download.', null=True, upload_to='ferramentas_pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='autor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Autor/Fonte'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='habilidades_desenvolvidas',
            field=models.CharField(blank=True, help_text='Ex: Comunicação, Interação Social, Coordenação Motora', max_length=255, null=True, verbose_name='Habilidades Desenvolvidas'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Imagem que aparecerá no card da ferramenta.', null=True, upload_to='ferramentas_capas/', verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='publico_alvo',
            field=models.CharField(blank=True, choices=[('pais_familiares', 'Pais e Familiares'), ('professores', 'Professores'), ('terapeutas', 'Terapeutas'), ('criancas_jovens', 'Crianças e Jovens'), ('todos', 'Todos os Públicos')], max_length=50, null=True, verbose_name='Público-Alvo'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='classificacao',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Classificação (0.0 a 5.0)'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='eh_gratuita',
            field=models.BooleanField(default=True, verbose_name='É Gratuita?'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='icone_classe',
            field=models.CharField(default='fas fa-tools', max_length=50, verbose_name='Ícone (Classe Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome da Ferramenta'),
        ),
    ]
