# Generated by Django 5.0.6 on 2025-08-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ferramenta_arquivo_pdf_ferramenta_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacontato',
            name='slug',
            field=models.SlugField(blank=True, help_text='Deixe em branco para gerar automaticamente a partir do nome.', max_length=100, null=True, unique=True),
        ),
    ]
