# Generated by Django 5.0.6 on 2025-08-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoriacontato_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacontato',
            name='slug',
        ),
    ]
