# Generated by Django 5.0.6 on 2025-08-17 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_categoriacontato_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodesempenho',
            name='aprendizagem_academica',
            field=models.IntegerField(blank=True, help_text='Nota de 1 a 10 para aprendizagem (leitura, escrita, matemática, atenção).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Aprendizagem Acadêmica'),
        ),
        migrations.AddField(
            model_name='relatoriodesempenho',
            name='autonomia',
            field=models.IntegerField(blank=True, help_text='Nota de 1 a 10 para autonomia (realizar tarefas sozinho, organizar materiais).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Autonomia'),
        ),
        migrations.AddField(
            model_name='relatoriodesempenho',
            name='comportamento_adaptativo',
            field=models.IntegerField(blank=True, help_text='Nota de 1 a 10 para comportamento (respeito a regras, controle de crises, transições).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Comportamento Adaptativo'),
        ),
        migrations.AddField(
            model_name='relatoriodesempenho',
            name='comunicacao_social',
            field=models.IntegerField(blank=True, help_text='Nota de 1 a 10 para comunicação (responder, interagir, iniciar diálogos).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Comunicação Social'),
        ),
        migrations.AddField(
            model_name='relatoriodesempenho',
            name='interacao_colegas',
            field=models.IntegerField(blank=True, help_text='Nota de 1 a 10 para interação (participação em grupo, jogos, atividades coletivas).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Interação com Colegas'),
        ),
    ]
