# Generated by Django 5.0.6 on 2025-08-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_relatoriodesempenho_aprendizagem_academica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodesempenho',
            name='aprendizagem_academica',
        ),
        migrations.RemoveField(
            model_name='relatoriodesempenho',
            name='autonomia',
        ),
        migrations.RemoveField(
            model_name='relatoriodesempenho',
            name='comportamento_adaptativo',
        ),
        migrations.RemoveField(
            model_name='relatoriodesempenho',
            name='comunicacao_social',
        ),
        migrations.RemoveField(
            model_name='relatoriodesempenho',
            name='interacao_colegas',
        ),
    ]
